#!/usr/bin/env python3
"""
Build content/bundle.js so the site works when index.html is opened
directly from disk (file://), with no local server.

Why this exists:
    The page normally loads its text from content/*.json and
    content/prose/**/*.md using fetch(). Browsers block fetch() of local
    files under the file:// protocol, so double-clicking index.html would
    otherwise show an empty page. This script embeds every content file
    into a single classic <script> (window.__CONTENT__), which the browser
    *is* allowed to read from disk. app.js uses that bundle as a fallback
    when fetch() isn't available.

Usage:
    python3 scripts/build_bundle.py

Re-run this whenever you edit anything under content/ AND you want the
double-click (file://) preview to reflect the change. When the site is
served over HTTP (local server or a real host), fetch() is used instead
and the bundle is ignored, so you don't need to rebuild for that.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONTENT = REPO / "content"
OUT = CONTENT / "bundle.js"


def main() -> None:
    if not CONTENT.is_dir():
        raise SystemExit(f"content/ not found at {CONTENT}")

    bundle: dict[str, object] = {}

    # JSON files directly under content/ (parsed -> embedded as JS objects)
    for path in sorted(CONTENT.glob("*.json")):
        key = path.relative_to(REPO).as_posix()
        bundle[key] = json.loads(path.read_text(encoding="utf-8"))

    # Markdown files under content/prose/** (embedded as strings)
    for path in sorted((CONTENT / "prose").rglob("*.md")):
        key = path.relative_to(REPO).as_posix()
        bundle[key] = path.read_text(encoding="utf-8")

    payload = json.dumps(bundle, ensure_ascii=False, indent=2)
    header = (
        "/* AUTO-GENERATED by scripts/build_bundle.py - do not edit by hand.\n"
        "   Lets the site work when index.html is opened directly (file://).\n"
        "   Re-run the script after editing anything under content/. */\n"
    )
    OUT.write_text(f"{header}window.__CONTENT__ = {payload};\n", encoding="utf-8")

    n_json = sum(1 for k in bundle if k.endswith(".json"))
    n_md = sum(1 for k in bundle if k.endswith(".md"))
    print(f"wrote {OUT.relative_to(REPO)}  ({n_json} JSON + {n_md} markdown files)")


if __name__ == "__main__":
    main()
