#!/usr/bin/env -S npx tsx
/**
 * Build content/bundle.js so the site works when index.html is opened
 * directly from disk (file://), with no local server.
 *
 * Why this exists:
 *   The page normally loads its text from content/*.json and
 *   content/prose/**\/*.md using fetch(). Browsers block fetch() of local
 *   files under the file:// protocol, so double-clicking index.html would
 *   otherwise show an empty page. This script embeds every content file
 *   into a single classic <script> (window.__CONTENT__), which the browser
 *   *is* allowed to read from disk. src/app.ts uses that bundle as a
 *   fallback when fetch() isn't available.
 *
 * Usage:
 *   npm run bundle:content
 *
 * Re-run this whenever you edit anything under content/ AND you want the
 * double-click (file://) preview to reflect the change. When the site is
 * served over HTTP (local server or a real host), fetch() is used instead
 * and the bundle is ignored, so you don't need to rebuild for that.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const CONTENT = join(REPO, 'content');
const OUT = join(CONTENT, 'bundle.js');

const toPosix = (path: string): string => relative(REPO, path).split(sep).join('/');

const walk = (dir: string): string[] => {
  const entries = readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
};

const main = (): void => {
  if (!existsSync(CONTENT)) throw new Error(`content/ not found at ${CONTENT}`);

  const bundle: Record<string, unknown> = {};

  // JSON files directly under content/ (parsed -> embedded as JS objects)
  const jsonFiles = readdirSync(CONTENT, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.json'))
    .map((e) => join(CONTENT, e.name))
    .sort();
  for (const file of jsonFiles) {
    bundle[toPosix(file)] = JSON.parse(readFileSync(file, 'utf-8'));
  }

  // Markdown files under content/prose/** (embedded as strings)
  const proseDir = join(CONTENT, 'prose');
  if (existsSync(proseDir)) {
    const mdFiles = walk(proseDir).filter((f) => f.endsWith('.md')).sort();
    for (const file of mdFiles) {
      bundle[toPosix(file)] = readFileSync(file, 'utf-8');
    }
  }

  const payload = JSON.stringify(bundle, null, 2);
  const header = '/* AUTO-GENERATED by scripts/build_bundle.ts - do not edit by hand.\n'
    + '   Lets the site work when index.html is opened directly (file://).\n'
    + '   Re-run `npm run bundle:content` after editing anything under content/. */\n';
  writeFileSync(OUT, `${header}window.__CONTENT__ = ${payload};\n`, 'utf-8');

  const keys = Object.keys(bundle);
  const nJson = keys.filter((k) => k.endsWith('.json')).length;
  const nMd = keys.filter((k) => k.endsWith('.md')).length;
  console.log(`wrote ${relative(REPO, OUT)}  (${nJson} JSON + ${nMd} markdown files)`);
};

main();
